version = 0.1

[default.deploy.parameters]
stack_name = "ecostream-ai-forecasting"
resolve_s3 = true
resolve_image_repos = true
s3_prefix = "ecostream-ai-forecasting"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
parameter_overrides = "S3LogBucket=ecostream-forecast-logs-052443862699 DynamoDbTableName=ecostream-telemetry-local"

[default.build.parameters]
use_container = false
