package com.ecostream.order.entity;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;

import java.util.UUID;

/**
 * Unit tests for Order entity.
 * Validates entity creation, field assignments, and status transitions.
 */
@DisplayName("Order Entity Tests")
class OrderTest {

    @Test
    @DisplayName("Should create Order with all required fields")
    void shouldCreateOrderWithAllFields() {
        // Given
        UUID id = UUID.randomUUID();
        OrderStatus status = OrderStatus.PENDING;
        double latitude = 40.7128;
        double longitude = -74.0060;
        int priority = 5;

        // When
        Order order = Order.builder()
                .id(id)
                .status(status)
                .destinationLatitude(latitude)
                .destinationLongitude(longitude)
                .priority(priority)
                .build();

        // Then
        assertNotNull(order);
        assertEquals(id, order.getId());
        assertEquals(status, order.getStatus());
        assertEquals(latitude, order.getDestinationLatitude());
        assertEquals(longitude, order.getDestinationLongitude());
        assertEquals(priority, order.getPriority());
    }

    @Test
    @DisplayName("Should allow creating Order without explicit ID")
    void shouldAllowCreatingOrderWithoutExplicitId() {
        // When - ID will be null until persisted to database
        Order order = Order.builder()
                .status(OrderStatus.PENDING)
                .destinationLatitude(40.7128)
                .destinationLongitude(-74.0060)
                .priority(1)
                .build();

        // Then - ID can be null before persistence (will be generated by JPA on save)
        assertNotNull(order);
        assertEquals(OrderStatus.PENDING, order.getStatus());
        // Note: ID will be generated by JPA @GeneratedValue when entity is persisted
    }

    @Test
    @DisplayName("Should allow status updates")
    void shouldAllowStatusUpdates() {
        // Given
        Order order = Order.builder()
                .status(OrderStatus.PENDING)
                .destinationLatitude(40.7128)
                .destinationLongitude(-74.0060)
                .priority(1)
                .build();

        // When
        order.setStatus(OrderStatus.IN_TRANSIT);

        // Then
        assertEquals(OrderStatus.IN_TRANSIT, order.getStatus());
    }
}
